name: Crave Builder(self-hosted)
on:
  workflow_dispatch:
    inputs:
      BASE_PROJECT:
        description: 'Choose a base project:'
        required: true
        default: 'LineageOS 17.1'
        type: choice
        options:
          - 'LineageOS 17.1'
      DEVICE_NAME:
        description: "Device's codename:"
        required: true
        default: "OP4C7D"
      PRODUCT_NAME:
        description: "Product to build:"
        required: true
        default: "lineage_OP4C7D"
      LOCAL_MANIFEST:
        description: "Personal local manifest [repository]:"
        required: true
        default: 'https://github.com/ansh-m14x/aosp_device_oppo_OP4C7D'
      LOCAL_MANIFEST_BRANCH:
        description: "Branch of local manifest:"
        required: true
        default: 'main'
      BUILD_COMMAND:
        description: 'Command for compiling:'
        required: true
        default: 'mka bacon'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      PROJECTFOLDER: ${{ steps.vars.outputs.PROJECTFOLDER }}
      REPO_INIT: ${{ steps.vars.outputs.REPO_INIT }}
      LOCAL_MANIFEST: ${{ steps.vars.outputs.LOCAL_MANIFEST }}
      LUNCH: ${{ steps.vars.outputs.LUNCH }}
    steps:
    - id: vars
      run: |
        echo "PROJECTFOLDER=/crave-devspaces/Lineage17" >> "$GITHUB_OUTPUT"
        echo "REPO_INIT=repo init -u https://github.com/LineageOS/android.git -b lineage-17.1 --git-lfs --depth=1" >> "$GITHUB_OUTPUT"
        echo "LOCAL_MANIFEST=git clone ${{ github.event.inputs.LOCAL_MANIFEST }} --depth 1 -b ${{ github.event.inputs.LOCAL_MANIFEST_BRANCH }} .repo/local_manifests" >> "$GITHUB_OUTPUT"
        echo "LUNCH=breakfast ${{ github.event.inputs.PRODUCT_NAME }} userdebug" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    runs-on: self-hosted
    steps:
    - name: Build Execution
      run: |
        # 1. Purana kachra saaf karo
        rm -rf *
        
        # 2. Crave configuration file manually banao
        cat <<EOF > crave.conf
        os: "android"
        project: "${{ needs.prepare.outputs.PROJECTFOLDER }}"
        EOF
        
        # 3. Crave run command - bina git init ke configuration file use karke
        crave run --config crave.conf --no-patch -- "
          rm -rf .repo/local_manifests/ ; \
          ${{ needs.prepare.outputs.REPO_INIT }} ; \
          ${{ needs.prepare.outputs.LOCAL_MANIFEST }} ; \
          /opt/crave/resync.sh ; \
          source build/envsetup.sh ; \
          ${{ needs.prepare.outputs.LUNCH }} ; \
          ${{ github.event.inputs.BUILD_COMMAND }}
        "
